server:
  servlet:
    context-path: /motor-mingle

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///database
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DATABASE_INSTANCE}

  liquibase:
    parameters:
      changeLogFile: src/main/resources/db/changelog/db.changelog-master.xml
