server:
  servlet:
    context-path: /motor-mingle

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATABASE_PASSWORD}
    url: jdbc:mysql:///database
    username: ${DATABASE_USERNAME}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.mysql.SocketFactory
        cloudSqlInstance: ${DATABASE_INSTANCE}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  session:
    jdbc:
      initialize-schema: always