server:
  servlet:
    context-path: /motor-mingle

spring:
  data:
    jdbc:
      repositories:
        enabled: false

  session:
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/motor-mingle-auth
          audiences: motor-mingle-auth
---
spring:
  config:
    activate:
      on-profile: gcp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///database
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DATABASE_INSTANCE}

  liquibase:
    parameters:
      changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/motormingle
    username: motormingle
    password: motormingle

  liquibase:
    parameters:
      changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml

    change-log: db/changelog/db.changelog-master.yaml
  mvc:
    log-request-details: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        web: DEBUG
        client:
          RestTemplate: DEBUG