@startuml

autonumber

actor "User" #red
entity "Mobile application" #blue
entity "Identity provider" #yellow
entity "API" #green

"User" -> "Mobile application": Click login
"Mobile application" -> "Mobile application": Generate code verifier and code challenge
"Mobile application" -> "Identity provider": Auhorization code + code challenge
"Identity provider" --> "User": Authorization prompt
"User" -> "Identity provider": Authorize and consent
"Identity provider" --> "Mobile application": Authorization code
"Mobile application" -> "Identity provider": Authorization code + code verifier
"Identity provider" -> "Identity provider": Validate code verifier and challenge
"Identity provider" --> "API": ID token and access token
"API" -> "API": Create user profile
"API" --> "Mobile application": Response
@enduml
