@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class car {
   capacity: numeric(1,3)
   id: bigint
}
class country {
   name: varchar(50)
   id: varchar(3)
}
class databasechangelog {
   id: varchar(255)
   author: varchar(255)
   filename: varchar(255)
   dateexecuted: timestamp
   orderexecuted: integer
   exectype: varchar(10)
   md5sum: varchar(35)
   description: varchar(255)
   comments: varchar(255)
   tag: varchar(255)
   liquibase: varchar(20)
   contexts: varchar(255)
   labels: varchar(255)
   deployment_id: varchar(10)
}
class databasechangeloglock {
   locked: boolean
   lockgranted: timestamp
   lockedby: varchar(255)
   id: integer
}
class encounter {
   hash: varchar(255)
   count: integer
   date: date
   status: varchar(255)
   user_id_1: uuid
   user_id_2: uuid
}
class manufacturer {
   name: varchar(50)
   country_id: varchar(3)
   id: bigint
}
class motorbike {
   capacity: integer
   motorbike_type_id: integer
   id: bigint
}
class motorbike_type {
   name: varchar(50)
   id: integer
}
class ownership {
   user_id: uuid
   vehicle_id: bigint
}
class photo {
   content: oid
   ownership_user_id: uuid
   ownership_vehicle_id: integer
   id: bigint
   user_id: uuid
   vehicle_id: integer
}
class user {
   email: varchar(50)
   tag: varchar(50)
   first_name: varchar(50)
   last_name: varchar(50)
   birth_date: date
   minimal_age: integer
   maximal_age: integer
   id: uuid
}
class vehicle {
   model: varchar(50)
   year: integer
   horse_power: integer
   manufacturer_id: bigint
   id: bigint
}

car                    -[#595959,plain]-^  vehicle               : "id"
encounter              -[#595959,plain]-^  user                  : "user_id_2:id"
encounter              -[#595959,plain]-^  user                  : "user_id_1:id"
manufacturer           -[#595959,plain]-^  country               : "country_id:id"
motorbike              -[#595959,plain]-^  motorbike_type        : "motorbike_type_id:id"
motorbike              -[#595959,plain]-^  vehicle               : "id"
ownership              -[#595959,plain]-^  user                  : "user_id:id"
ownership              -[#595959,plain]-^  vehicle               : "vehicle_id:id"
photo                  -[#595959,plain]-^  ownership             : "ownership_user_id, ownership_vehicle_id:user_id, vehicle_id"
photo                  -[#595959,plain]-^  user                  : "user_id:id"
photo                  -[#595959,plain]-^  vehicle               : "vehicle_id:id"
vehicle                -[#595959,plain]-^  manufacturer          : "manufacturer_id:id"
@enduml
